import {Member} from './models/member';

export const MEMBERS: Member[] = [
  new Member().deserialize({
    id: 1,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: false
  }),
  new Member().deserialize({
    id: 2,
    first_name: 'Paco',
    last_name: 'Rabanne',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: true
  }),
  new Member().deserialize({
    id: 3,
    first_name: 'Ricardo Manuel',
    last_name: 'Romaní Azpilicueta del Rio',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: true
  }),
  new Member().deserialize({
    id: 4,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: false
  }),
  new Member().deserialize({
    id: 5,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: false
  }),
  new Member().deserialize({
    id: 6,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: false
  }),
  new Member().deserialize({
    id: 7,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: false
  }),
  new Member().deserialize({
    id: 8,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: true
  }),
  new Member().deserialize({
    id: 9,
    first_name: 'Ricardo',
    last_name: 'Romaní',
    alias: 'Richi',
    number: 6,
    nif: '12345678A',
    sex: 'H',
    birth: new Date(),
    email: 'rromani@prueba.com',
    street: 'Calle Arconte, Nº29 - 3ºB',
    city: 'Santiago de Compostela',
    postal_code: 19840,
    province: 'A Coruña',
    primary_phone: '636111222',
    secondary_phone: '677888999',
    moto1: 'Honda CBR 600 F',
    moto2: 'Aprilia RS 125 2T',
    moto3: 'Ducati Monster 650',
    photo_person: '',
    photo_moto: '',
    avatar: '',
    created: new Date(),
    updated: new Date(),
    updated_by: 'rromani',
    pending_paids: true
  }),
];
